import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/shared/header/header";
import Footer from "../components/shared/footer/footer";
import { ToastContainer } from "react-toastify";

const montserratRegular = localFont({
  src: './fonts/montserrat.light.ttf',
  variable: '--font-montserrat-regular',
})

const montserratMedium = localFont({
  src: './fonts/montserrat.medium.ttf',
  variable: '--font-montserrat-medium ',
})
const montserratBold = localFont({
  src: './fonts/montserrat.bold.ttf',
  variable: '--font-montserrat-bold',
})

const montserratExtrabold = localFont({
  src: './fonts/montserrat.extrabold.ttf',
  variable: '--font-montserrat-extrabold ',
})
const montserratSemibold = localFont({
  src: './fonts/montserrat.semibold.ttf',
  variable: '--font-montserrat-semibold',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${montserratRegular.variable} ${montserratMedium.variable} ${montserratBold.variable} ${montserratExtrabold.variable} ${montserratSemibold.variable} bg-white text-black`}
      >
        <header>
          <Header />
        </header>
        <main className="min-h-screen">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
         <ToastContainer position="top-center" />
      </body>
    </html>
  );
}
